INSERT INTO "ACCOUNT"
("accountNumber", "password")
VALUES
('JOHN.SMITH_13', 'vddkborn@43t23');

INSERT INTO "PERSONAL_ACCOUNT"
("accountNumber")
VALUES
('JOHN.SMITH_13');

INSERT INTO "ASSOCIATED_ACCOUNTS"
("accountNumber1", "accountNumber2" )
VALUES
('PEPA.DVORAK_23' , 'JOHN.SMITH_13');



SELECT * FROM "PERSONAL_ACCOUNT";
SELECT * FROM "ASSOCIATED_ACCOUNTS";
