DROP TABLE "USER" CASCADE CONSTRAINTS;
DROP TABLE "ADVERTISEMENT" CASCADE CONSTRAINTS;
DROP TABLE "COMPANY_ACCOUNT" CASCADE CONSTRAINTS;
DROP TABLE "PERSONAL_ACCOUNT" CASCADE CONSTRAINTS;
DROP TABLE "PERMISSIONS" CASCADE CONSTRAINTS;
DROP TABLE "PAGE" CASCADE CONSTRAINTS;
DROP TABLE "ACCOUNT" CASCADE CONSTRAINTS;
DROP TABLE "ASSOCIATED_ACCOUNTS" CASCADE CONSTRAINTS;